[project]
name = "agno-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.7.9",
    "groq>=0.31.0",
    "ipykernel>=6.30.1",
    "tavily-python>=0.7.10",
    "yfinance>=0.2.65",
]
